GETTEXT_LIB_BASE_SRCS =	\
	acl-errno-valid.c	\
	acl-internal.c	\
	addext.c	\
	allocator.c	\
	areadlink.c	\
	argmatch.c	\
	asnprintf.c	\
	asprintf.c	\
	backupfile.c	\
	basename-lgpl.c	\
	basename.c	\
	binary-io.c	\
	c-ctype.c	\
	c-strcasecmp.c	\
	c-strcasestr.c	\
	c-strncasecmp.c	\
	c-strstr.c	\
	canonicalize-lgpl.c	\
	careadlinkat.c	\
	classpath.c	\
	clean-temp.c	\
	cloexec.c	\
	close.c	\
	closedir.c	\
	closeout.c	\
	concat-filename.c	\
	copy-acl.c	\
	copy-file.c	\
	csharpcomp.c	\
	csharpexec.c	\
	dirfd.c	\
	dirname-lgpl.c	\
	dup-safer-flag.c	\
	dup-safer.c	\
	dup2.c	\
	error-progname.c	\
	error.c	\
	execute.c	\
	exitfail.c	\
	fatal-signal.c	\
	fcntl.c	\
	fd-hook.c	\
	fd-safer-flag.c	\
	fd-safer.c	\
	findprog.c	\
	fnmatch.c	\
	fopen.c	\
	fstat.c	\
	fstrcmp.c	\
	ftell.c	\
	ftello.c	\
	full-write.c	\
	fwriteerror.c	\
	gcd.c	\
	get-permissions.c	\
	getdelim.c	\
	getdtablesize.c	\
	getline.c	\
	getopt.c	\
	getopt1.c	\
	getprogname.c	\
	gettime.c	\
	gettimeofday.c	\
	gl_linkedhash_list.c	\
	gl_list.c	\
	gl_xlist.c	\
	hard-locale.c	\
	hash.c	\
	isinf.c	\
	isnand.c	\
	isnanf.c	\
	isnanl.c	\
	javacomp.c	\
	javaexec.c	\
	javaversion.c	\
	localcharset.c	\
	localename-table.c	\
	localename.c	\
	localtime-buffer.c	\
	localtime.c	\
	lseek.c	\
	malloc.c	\
	malloca.c	\
	math.c	\
	mbchar.c	\
	mbiter.c	\
	mbrtowc.c	\
	mbsinit.c	\
	mbslen.c	\
	mbsrtowcs-state.c	\
	mbsrtowcs.c	\
	mbsstr.c	\
	mbswidth.c	\
	mbuiter.c	\
	mkdir.c	\
	mkdtemp.c	\
	msvc-inval.c	\
	msvc-nothrow.c	\
	obstack.c	\
	omp-init.c	\
	open.c	\
	opendir.c	\
	pipe-filter-aux.c	\
	pipe-filter-ii.c	\
	pipe-safer.c	\
	pipe2-safer.c	\
	pipe2.c	\
	printf-args.c	\
	printf-parse.c	\
	progname.c	\
	progreloc.c	\
	propername.c	\
	qcopy-acl.c	\
	qset-acl.c	\
	quotearg.c	\
	raise.c	\
	rawmemchr.c	\
	read-file.c	\
	read.c	\
	readdir.c	\
	readlink.c	\
	realloc.c	\
	relocatable.c	\
	relocwrapper.c	\
	rmdir.c	\
	safe-read.c	\
	safe-write.c	\
	secure_getenv.c	\
	set-acl.c	\
	set-permissions.c	\
	setenv.c	\
	setlocale.c	\
	sh-quote.c	\
	sig-handler.c	\
	sigaction.c	\
	sigprocmask.c	\
	snprintf.c	\
	spawn-pipe.c	\
	spawnattr_destroy.c	\
	spawnattr_init.c	\
	spawnattr_setflags.c	\
	spawnattr_setsigmask.c	\
	spawni.c	\
	spawnp.c	\
	spawn_faction_addclose.c	\
	spawn_faction_adddup2.c	\
	spawn_faction_addopen.c	\
	spawn_faction_destroy.c	\
	spawn_faction_init.c	\
	stat-time.c	\
	stat-w32.c	\
	stat.c	\
	stdio-write.c	\
	stpcpy.c	\
	stpncpy.c	\
	strchrnul.c	\
	strerror-override.c	\
	strerror.c	\
	striconv.c	\
	striconveh.c	\
	striconveha.c	\
	stripslash.c	\
	strnlen1.c	\
	strstr.c	\
	tempname.c	\
	timespec.c	\
	tmpdir.c	\
	trim.c	\
	unistd.c	\
	unsetenv.c	\
	utime.c	\
	utimens.c	\
	vasnprintf.c	\
	vasprintf.c	\
	vsnprintf.c	\
	wait-process.c	\
	waitpid.c	\
	wctype-h.c	\
	wcwidth.c	\
	write.c	\
	xasprintf.c	\
	xconcat-filename.c	\
	xerror.c	\
	xmalloc.c	\
	xmalloca.c	\
	xmemdup0.c	\
	xreadlink.c	\
	xsetenv.c	\
	xsize.c	\
	xstrdup.c	\
	xstriconv.c	\
	xstriconveh.c	\
	xvasprintf.c	\

!if $(VSVER) < 12
GETTEXT_LIB_BASE_SRCS =	\
	$(GETTEXT_LIB_BASE_SRCS)	\
	iswblank.c	\
	signbitd.c	\
	signbitf.c	\
	signbitl.c
!endif

LIBGREP_SOURCES =	\
	..\libgrep\kwset.c	\
	..\libgrep\localeconv.c	\
	..\libgrep\m-fgrep.c	\
	..\libgrep\m-regex.c	\
	..\libgrep\mbrlen.c	\
	..\libgrep\nl_langinfo.c	\
	..\libgrep\regex.c	\
	..\libgrep\wcrtomb.c

LIBGETTEXTPO_GNULIB_SRCS =	\
	..\gnulib-lib\libgettextpo\asnprintf.c	\
	..\gnulib-lib\libgettextpo\asprintf.c	\
	..\gnulib-lib\libgettextpo\basename-lgpl.c	\
	..\gnulib-lib\libgettextpo\basename.c	\
	..\gnulib-lib\libgettextpo\c-ctype.c	\
	..\gnulib-lib\libgettextpo\c-strcasecmp.c	\
	..\gnulib-lib\libgettextpo\c-strncasecmp.c	\
	..\gnulib-lib\libgettextpo\c-strstr.c	\
	..\gnulib-lib\libgettextpo\cloexec.c	\
	..\gnulib-lib\libgettextpo\close.c	\
	..\gnulib-lib\libgettextpo\concat-filename.c	\
	..\gnulib-lib\libgettextpo\dirname-lgpl.c	\
	..\gnulib-lib\libgettextpo\dup2.c	\
	..\gnulib-lib\libgettextpo\error-progname.c	\
	..\gnulib-lib\libgettextpo\error.c	\
	..\gnulib-lib\libgettextpo\exitfail.c	\
	..\gnulib-lib\libgettextpo\fcntl.c	\
	..\gnulib-lib\libgettextpo\fd-hook.c	\
	..\gnulib-lib\libgettextpo\float.c	\
	..\gnulib-lib\libgettextpo\fopen.c	\
	..\gnulib-lib\libgettextpo\fstat.c	\
	..\gnulib-lib\libgettextpo\fstrcmp.c	\
	..\gnulib-lib\libgettextpo\fsync.c	\
	..\gnulib-lib\libgettextpo\fwriteerror.c	\
	..\gnulib-lib\libgettextpo\gcd.c	\
	..\gnulib-lib\libgettextpo\getdelim.c	\
	..\gnulib-lib\libgettextpo\getdtablesize.c	\
	..\gnulib-lib\libgettextpo\getline.c	\
	..\gnulib-lib\libgettextpo\getprogname.c	\
	..\gnulib-lib\libgettextpo\gl_linked_list.c	\
	..\gnulib-lib\libgettextpo\gl_list.c	\
	..\gnulib-lib\libgettextpo\gl_xlist.c	\
	..\gnulib-lib\libgettextpo\hard-locale.c	\
	..\gnulib-lib\libgettextpo\hash.c	\
	..\gnulib-lib\libgettextpo\localcharset.c	\
	..\gnulib-lib\libgettextpo\malloc.c	\
	..\gnulib-lib\libgettextpo\malloca.c	\
	..\gnulib-lib\libgettextpo\markup.c	\
	..\gnulib-lib\libgettextpo\mbrtowc.c	\
	..\gnulib-lib\libgettextpo\mbsinit.c	\
	..\gnulib-lib\libgettextpo\mbswidth.c	\
	..\gnulib-lib\libgettextpo\msvc-inval.c	\
	..\gnulib-lib\libgettextpo\msvc-nothrow.c	\
	..\gnulib-lib\libgettextpo\obstack.c	\
	..\gnulib-lib\libgettextpo\open.c	\
	..\gnulib-lib\libgettextpo\printf-args.c	\
	..\gnulib-lib\libgettextpo\printf-parse.c	\
	..\gnulib-lib\libgettextpo\raise.c	\
	..\gnulib-lib\libgettextpo\rawmemchr.c	\
	..\gnulib-lib\libgettextpo\realloc.c	\
	..\gnulib-lib\libgettextpo\relocatable.c	\
	..\gnulib-lib\libgettextpo\sigprocmask.c	\
	..\gnulib-lib\libgettextpo\stat-time.c	\
	..\gnulib-lib\libgettextpo\stat-w32.c	\
	..\gnulib-lib\libgettextpo\stat.c	\
	..\gnulib-lib\libgettextpo\stdio-write.c	\
	..\gnulib-lib\libgettextpo\stpcpy.c	\
	..\gnulib-lib\libgettextpo\stpncpy.c	\
	..\gnulib-lib\libgettextpo\strchrnul.c	\
	..\gnulib-lib\libgettextpo\strerror-override.c	\
	..\gnulib-lib\libgettextpo\strerror.c	\
	..\gnulib-lib\libgettextpo\striconv.c	\
	..\gnulib-lib\libgettextpo\striconveh.c	\
	..\gnulib-lib\libgettextpo\striconveha.c	\
	..\gnulib-lib\libgettextpo\stripslash.c	\
	..\gnulib-lib\libgettextpo\strstr.c	\
	..\gnulib-lib\libgettextpo\unistd.c	\
	..\gnulib-lib\libgettextpo\vasnprintf.c	\
	..\gnulib-lib\libgettextpo\vasprintf.c	\
	..\gnulib-lib\libgettextpo\wctype-h.c	\
	..\gnulib-lib\libgettextpo\wcwidth.c	\
	..\gnulib-lib\libgettextpo\xasprintf.c	\
	..\gnulib-lib\libgettextpo\xconcat-filename.c	\
	..\gnulib-lib\libgettextpo\xerror.c	\
	..\gnulib-lib\libgettextpo\xmalloc.c	\
	..\gnulib-lib\libgettextpo\xmalloca.c	\
	..\gnulib-lib\libgettextpo\xsize.c	\
	..\gnulib-lib\libgettextpo\xstrdup.c	\
	..\gnulib-lib\libgettextpo\xstriconv.c	\
	..\gnulib-lib\libgettextpo\xvasprintf.c

LIBGETTEXTPO_AUX_SRCS =	\
	..\src\str-list.c \
	..\src\dir-list.c \
	..\src\message.c \
	..\src\msgl-ascii.c \
	..\src\po-error.c \
	..\src\po-xerror.c \
	..\src\write-catalog.c \
	..\src\write-po.c \
	..\src\open-catalog.c \
	..\src\po-charset.c \
	..\src\po-lex.c \
	..\src\po-gram-gen.c \
	..\src\read-po.c \
	..\src\read-catalog-abstract.c \
	..\src\read-catalog.c \
	..\src\plural-table.c \
	..\src\format-c.c \
	..\src\format-sh.c \
	..\src\format-python.c \
	..\src\format-python-brace.c \
	..\src\format-lisp.c \
	..\src\format-elisp.c \
	..\src\format-librep.c \
	..\src\format-scheme.c \
	..\src\format-java.c \
	..\src\format-javascript.c \
	..\src\format-csharp.c \
	..\src\format-awk.c \
	..\src\format-pascal.c \
	..\src\format-ycp.c \
	..\src\format-tcl.c \
	..\src\format-perl.c \
	..\src\format-perl-brace.c \
	..\src\format-php.c \
	..\src\format-gcc-internal.c \
	..\src\format-gfc-internal.c \
	..\src\format-qt.c \
	..\src\format-qt-plural.c \
	..\src\format-kde.c \
	..\src\format-kde-kuit.c \
	..\src\format-boost.c \
	..\src\format-lua.c \
	..\src\format.c \
	..\src\plural-exp.c \
	..\src\plural-eval.c \
	..\src\msgl-check.c \
	..\src\sentence.c